server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://212.64.112.148:3306/activiti
    username: root
    password: HCYswez123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activiti:
    db-history-used: true
    database-schema-update: true
    check-process-definitions: true
